# Generated by Django 3.2.9 on 2021-11-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event_type')),
            ],
        ),
        migrations.DeleteModel(
            name='Event_Date',
        ),
    ]
