# Generated by Django 3.2.9 on 2021-11-19 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211118_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(max_length=50)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='Entry',
            new_name='event_type',
        ),
        migrations.CreateModel(
            name='Application_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField()),
                ('application_log', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.application_log')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.entry')),
            ],
        ),
    ]
