# Generated by Django 3.2.9 on 2021-11-20 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211120_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_log',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application_info',
            name='application_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.application_log'),
        ),
        migrations.AlterField(
            model_name='application_info',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
