# Generated by Django 3.2.9 on 2021-11-26 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20211122_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=40)),
                ('participant', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='event_type',
            old_name='name',
            new_name='type_name',
        ),
        migrations.RemoveField(
            model_name='application_info',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='event_type',
        ),
        migrations.AddField(
            model_name='application_log',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event_type',
            name='application_log',
            field=models.ManyToManyField(blank=True, to='events.Application_Log'),
        ),
        migrations.AddField(
            model_name='event_type',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='application_info',
            name='participant',
        ),
        migrations.AddField(
            model_name='application_info',
            name='participant',
            field=models.ManyToManyField(blank=True, to='events.Participant'),
        ),
    ]
