# Generated by Django 3.2.9 on 2021-11-29 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20211127_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='event_type',
            name='application_log',
        ),
        migrations.AddField(
            model_name='application_info',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='application_info',
            name='entry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='events.entry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application_info',
            name='event_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='events.event_type'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='application_info',
            name='participant',
        ),
        migrations.AddField(
            model_name='application_info',
            name='participant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='events.participant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Application_Log',
        ),
        migrations.AlterField(
            model_name='participant',
            name='line_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.line_name'),
        ),
    ]
