# Generated by Django 3.2.9 on 2021-12-01 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20211130_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_info',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.entry'),
        ),
        migrations.AlterField(
            model_name='application_info',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event_type'),
        ),
        migrations.AlterField(
            model_name='application_info',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.participant'),
        ),
    ]
