# Generated by Django 3.2.9 on 2022-01-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20211201_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_type',
            name='pic_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='event_type',
            name='type_name',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='line_name',
            name='line_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant',
            field=models.CharField(default='', max_length=50),
        ),
    ]
