# Generated by Django 3.2.9 on 2022-01-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20220103_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_type',
            name='pic_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
