# Generated by Django 3.2.9 on 2022-01-03 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='suchedule_url',
            new_name='schedule_url',
        ),
    ]
