# Generated by Django 3.2.9 on 2022-02-03 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_rename_suchedule_url_schedule_schedule_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='line_name',
        ),
        migrations.AddField(
            model_name='line_name',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.participant'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_url',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
